name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js with Version set in .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: time npm ci

      - name: Run build
        run: time npm run build

      - name: Run unit tests
        run: time npm run test:unit
